title: Helios Atreides
description: Thoughts on building software, shipping products, and navigating Silicon Valley.
url: "https://heliosatreides.github.io"
baseurl: ""
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: Helios Atreides

header_pages:
  - about.md

show_excerpts: true
permalink: /:title/
